on:
  push:
    branches:
      - master
    paths-ignore:
      - test/**
      - gradlew
      - gradlew.bat
      - .gitignore
      - '*.md'

jobs:
  push_image:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
      url: https://spacemaven.derfruhling.net
    steps:
      - uses: actions/checkout@v4
      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure Docker to push to gcloud
        run: gcloud auth configure-docker ${{ secrets.GCP_LOCATION }}-docker.pkg.dev
      - name: Build Docker image
        run: docker build --tag=${{ secrets.GCP_DOCKER_REGISTRY }}/server:${{ github.ref_name }} .
      - name: Push Docker image
        run: docker push ${{ secrets.GCP_DOCKER_REGISTRY }}/server:${{ github.ref_name }}
      - name: Deploy to GCP
        run: gcloud run deploy ${{ secrets.GCP_RUN_SERVICE_NAME }} --image ${{ secrets.GCP_DOCKER_REGISTRY }}/server:${{ github.ref_name }} --region ${{ secrets.GCP_RUN_REGIONS }} --platform managed --project ${{ secrets.GCP_PROJECT_ID }}
